version: '3.7'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks:
      - app-network
  redis:
    image: redis:7.0-alpine
    container_name: redis
    volumes:
      - 'redis:/data'
    networks:
      - app-network
  common: &common
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - 'bundle_cache:/bundle'
      - '.:/app'
    environment:
      REDIS_URL: ${REDIS_URL}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DISABLE_SPRING: 1
  app:
    <<: *common
    container_name: kingsmen
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - '${DOCKER_HOST_WEB_PORT:-3000}:3000'
  worker:
    <<: *common
    container_name: sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml

volumes:
  redis:
  postgres:
  bundle_cache:

networks:
  app-network:
    driver: bridge