# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.

name: "DO Droplet Build"
on:
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout files    
        uses: actions/checkout@v3

      - name: Get tag name
        id: tagName
        uses: olegtarasov/get-tag@v2

      - name: Get repo name
        id: repoName
        uses: MariachiBear/get-repo-name-action@v1.1.0

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
         
      - name: Provision Droplet and deploy container
        id: droplet
        run: >-
          echo "::set-output name=DROPLET_ID::$(
#            doctl compute droplet create "${{ steps.tagName.outputs.tag }}" --image docker-22-04 --size s-1vcpu-1gb --region nyc3 --user-data-file deploy.sh --wait --no-header --format=ID
            doctl compute droplet create "${{ steps.tagName.outputs.tag }}" --image docker-22-04 --size s-1vcpu-1gb --region nyc3 --user-data-file --wait --no-header --format=ID
          )"

      - name: Assign Droplet to Project
        run: doctl projects resources assign ${PROJECT_ID} --resource=do:droplet:"${{ steps.droplet.outputs.DROPLET_ID }}"

      - name: Rails Compile Assets
        run: ...