# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
name: "DigitalOcean Droplet Build"
on:
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Droplet Build Summary
        run: |
          echo "### DigitalOcean Droplet Build! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- We're going to build a DO droplet with the same name as our repo using doctl (and the appropriate token)" >> $GITHUB_STEP_SUMMARY
          echo "- The script do-cloud-config.sh configure a new user, ssh access and the droplet ufw" >> $GITHUB_STEP_SUMMARY

      - name: Checkout files    
        uses: actions/checkout@v3

      - name: Get Repo Name
        id: repoName
        run: echo "REPO_NAME = ${{ github.event.repository.name }}" >> $GITHUB_OUTPUT

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
         
      - name: Provision Droplet and deploy container
        id: droplet
        run: |
          droplet_id = $(doctl compute droplet create "${{ github.event.repository.name }}" --image docker-20-04 --size s-1vcpu-1gb --region nyc3 --user-data-file do-cloud-config.yml --wait --no-header --format=ID)
          exit_code = ${PIPESTATUS[0]}
          echo "DROPLET_ID = $droplet_id" >> $GITHUB_OUTPUT
          exit $exit_code

      - name: Assign Droplet to Project
        if: always()
        env:
          Project_Id: e63b9e3c-091f-4b0c-94c1-a42573dc7706
        run: doctl projects resources assign do:project:"$Project_Id" --resource=do:droplet:"${{ steps.droplet.outputs.DROPLET_ID }}"
