# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# use with precaution


name: "DO Droplet Build"
on:
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout files    
        uses: actions/checkout@v3

      - name: Print GitHub Repo Name
        run: echo "Repo - ${{ github.repository }}"

      - name: Print GitHub Owner
        run: echo "Owner - ${{ github.repository_owner }}"

      - name: Get repo name
        id: repoName
        uses: MariachiBear/get-repo-name-action@v1.1.0

      - name: Testing El Oso Mariachi Repo Name
        run: echo "MariachiBear - ${{ steps.repoName.outputs.repository-name }}"

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
         
#      - name: Provision Droplet and deploy container
#        id: droplet
#        run: >-
#          echo "DROPLET_ID = $(
#            doctl compute droplet create "${{ steps.repoName.outputs.repository-name }}" --image docker-22-04 --size s-1vcpu-1gb --region nyc3 --user-data-file --wait --no-header --format=ID
#          )" >> $GITHUB_OUTPUT


#      - name: Assign Droplet to Project
#        run: doctl projects resources assign ${PROJECT_ID} --resource=do:droplet:"${{ steps.droplet.outputs.DROPLET_ID }}"
